# Generated by Django 4.2.30 on 2026-06-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('idade', models.CharField(max_length=5)),
                ('funcao', models.CharField(max_length=50)),
                ('local_nasc', models.CharField(max_length=50)),
            ],
        ),
    ]
