# Generated by Django 6.0.5 on 2026-07-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_resumo', models.CharField(max_length=50)),
                ('resumo', models.TextField(max_length=200)),
                ('titulo_sobre', models.CharField(max_length=50)),
                ('sobre', models.TextField(max_length=200)),
                ('imagem', models.ImageField(upload_to='assets/')),
                ('titulo_autores', models.CharField(max_length=50)),
                ('autores', models.TextField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='elenco',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
