# Generated by Django 4.2.30 on 2026-07-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sobre_alter_elenco_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elenco',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='elenco',
            name='imagem',
            field=models.ImageField(upload_to='assets/'),
        ),
        migrations.AlterField(
            model_name='sobre',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
